name: pydata_toronto_aug2017
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - pandas
  - numpy
  - matplotlib
  - scipy
  - patsy
  - scikit-learn
  - seaborn
  - ipython
  - ipykernel
  - nb_conda
  - nb_conda_kernels
  - nbpresent
  - jupyter_core
  - openpyxl
  - xlrd
  - pytest
  - pip:
    - missingno
    - pandas_summary
